---
title: "DASHBOARD!"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=TRUE}
library(flexdashboard)
library(Lahman)
library(sqldf)
library(ggplot2)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Kenny Lofton Stolen Bases

```{r}
query<-"SELECT playerID,SB,yearID 
FROM Batting
WHERE playerID='loftoke01'"

result<-sqldf(query)

ggplot()+
  geom_histogram(data=result,aes(x=SB),color="blue", fill="white",bins=5)+
  ggtitle("Kenny Lofton's Stolen Bases")
```


Column {data-width=350}
-----------------------------------------------------------------------

### Kenny Lofton's Total Stolen Bases By Team

```{r}
query<-"SELECT playerID,sum(SB) AS total_SB,yearID,teamID 
FROM Batting
WHERE playerID='loftoke01'
GROUP BY teamID
ORDER BY sum(SB)"

result<-sqldf(query)

result$teamID<-factor(result$teamID,levels=result$teamID)

ggplot()+
  geom_bar(data=result,aes(x=teamID,y=total_SB),stat="identity",color="red",fill="blue")+
  #coord_flip()+
  ylab("Stolen Bases")+
  xlab("Team")+
  ggtitle("Kenny Lofton Stolen Bases By Team")
```

### Chart C

```{r}


```

